config/routes.rb
Rails.application.routes.draw do
  resources :shopdetails

  get 'welcome/index'

   root 'welcome#index'

   match 'shopAppPage', to: 'welcome#shopAppPage_1', via: [:get, :post] 
   match 'subscribePage', to: 'welcome#subscribePage', via: [:get, :post]
   match 'readArticlePage', to: 'welcome#readArticlePage', via: [:get, :post]
   

end

app/models/shopdetail.rb
class Shopdetail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shopdetails_controller.rb
class ShopdetailsController < ApplicationController
  before_action :set_shopdetail, only: [:show, :edit, :update, :destroy]

  # GET /shopdetails
  # GET /shopdetails.json
  def index
    @shopdetails = Shopdetail.all
  end

  # GET /shopdetails/1
  # GET /shopdetails/1.json
  def show
  end

  # GET /shopdetails/new
  def new
    @shopdetail = Shopdetail.new
  end

  # GET /shopdetails/1/edit
  def edit
  end

  # POST /shopdetails
  # POST /shopdetails.json
  def create
    @shopdetail = Shopdetail.new(shopdetail_params)

    respond_to do |format|
      if @shopdetail.save
        format.html { redirect_to @shopdetail, notice: 'Shopdetail was successfully created.' }
        format.json { render :show, status: :created, location: @shopdetail }
      else
        format.html { render :new }
        format.json { render json: @shopdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopdetails/1
  # PATCH/PUT /shopdetails/1.json
  def update
    respond_to do |format|
      if @shopdetail.update(shopdetail_params)
        format.html { redirect_to @shopdetail, notice: 'Shopdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopdetail }
      else
        format.html { render :edit }
        format.json { render json: @shopdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopdetails/1
  # DELETE /shopdetails/1.json
  def destroy
    @shopdetail.destroy
    respond_to do |format|
      format.html { redirect_to shopdetails_url, notice: 'Shopdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopdetail
      @shopdetail = Shopdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopdetail_params
      params[:shopdetail]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def shopAppPage_1
  end

  def subscribePage
  end

  def readArticlePage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shopdetails_helper.rb
module ShopdetailsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shopdetails/_form.html.erb
<%= form_for(@shopdetail) do |f| %>
  <% if @shopdetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopdetail.errors.count, "error") %> prohibited this shopdetail from being saved:</h2>

      <ul>
      <% @shopdetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopdetails/edit.html.erb
<h1>Editing shopdetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopdetail %> |
<%= link_to 'Back', shopdetails_path %>

app/views/shopdetails/index.html.erb
<h1>Listing shopdetails</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopdetails.each do |shopdetail| %>
      <tr>
        <td><%= link_to 'Show', shopdetail %></td>
        <td><%= link_to 'Edit', edit_shopdetail_path(shopdetail) %></td>
        <td><%= link_to 'Destroy', shopdetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopdetail', new_shopdetail_path %>

app/views/shopdetails/new.html.erb
<h1>New shopdetail</h1>

<%= render 'form' %>

<%= link_to 'Back', shopdetails_path %>

app/views/shopdetails/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_shopdetail_path(@shopdetail) %> |
<%= link_to 'Back', shopdetails_path %>

app/views/welcome/index.html.erb
<div  class="welcome">
	<h1>Welcome to Shop App</h1>
	<img src="/assets/shopping1.jpg">
</div>

<div class="container">
	<a href="/shopAppPage" class="link">Click to Enter</a>
</div>

app/views/welcome/readArticlePage.html.erb
<div class="navbar navbar-inverse navbar-static-top">

	<div class="container">

		<a href="/shopAppPage" class="navbar-brand">Shop App</a>

		<button class="navbar-toggle" data-toggle = "collapse" data-target=".navHeaderCollapse">

			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>

		</button>
		<div class="collapse navbar-collapse navHeaderCollapse">

			<ul class="nav navbar-nav navbar-right">

				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Blog</a></li>
				<li class="dropdown">

					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Social Media</a>
					<ul class="dropdown-menu">
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">Google+</a></li>
						<li><a href="#">Instragram</a></li>
					</ul>

				</li>
				<li><a href="#">About</a></li>
				<li><a href="#contact" data-toggle="modal">Contact</a></li>

			</ul>

		</div>

	</div>

</div>

<div class="container">
	<div class="row">
		<div class="col-lg-9">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="page-header">
						<h4>Mobo Mobo <small>Posted by Prabh</small></h4>
						<img src="/assets/typing.jpg" class="featuredImg">
						<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected. The view should just display that information. By default, view templates are written in a language called eRuby (Embedded Ruby) which is processed by the request cycle in Rails before being sent to the user.</p>
						<h4>Another Desc</h4>
						<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected. The view should just display that information. By default, view templates are written in a language called eRuby (Embedded Ruby) which is processed by the request cycle in Rails before being sent to the user.</p>
						<h4>Another Desc</h4>
						<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected. The view should just display that information. By default, view templates are written in a language called eRuby (Embedded Ruby) which is processed by the request cycle in Rails before being sent to the user.</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-3">
			<div class="list-group">
				<a href="#" class="list-group-item active">
					<h4 class="list-group-item-heading">Mobo Mobo</h4>
				<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected.</p>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Chapter 2</h4>
				<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected.</p>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Chapter 2</h4>
				<p>A view's purpose is to display this information in a human readable format. An important distinction to make is that it is the controller, not the view, where information is collected.</p>
				</a>
			</div>
		</div>
	</div>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
	<div class="container">
		<p class="navbar-text pull-left">Site by Prabhjot</p>
		<a href="/subscribePage" class="navbar-btn  btn-danger btn pull-right">Subscribe</a>
	</div>
</div>

<div id = "contact" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal">
				<div class="modal-header">
					<h4>Contact Us</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
								<label for="contact-name" class="col-lg-2 control-label">Name</label>
								<div class="col-lg-10">
									<input type="text" class="form-control" id="contact-name" placeholder="Full Name">
								</div>
					</div>
					<div class="form-group">
								<label for="contact-email" class="col-lg-2 control-label">Email</label>
								<div class="col-lg-10">
									<input type="text" class="form-control" id="contact-email" placeholder="you@example.com">
								</div>
					</div>
					<div class="form-group">
								<label for="message" class="col-lg-2 control-label">Message</label>
								<div class="col-lg-10">
									<textarea class="form-control" id="message" placeholder="" rows="8"></textarea>
								</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn btn-primary" type="submit">Send</button>
					<a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
				</div>
			</form>
		</div>
	</div>
</div>

app/views/welcome/shopAppPage_1.html.erb
<div class="navbar navbar-inverse navbar-static-top">

	<div class="container">

		<a href="/shopAppPage" class="navbar-brand">Shop App</a>

		<button class="navbar-toggle" data-toggle = "collapse" data-target=".navHeaderCollapse">

			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>

		</button>
		<div class="collapse navbar-collapse navHeaderCollapse">

			<ul class="nav navbar-nav navbar-right">

				<li class="active"><a href="#">Home</a></li>
				<li><a href="#">Blog</a></li>
				<li class="dropdown">

					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Social Media<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">Google+</a></li>
						<li><a href="#">Instragram</a></li>
					</ul>

				</li>
				<li><a href="#">About</a></li>
				<li><a href="#contact" data-toggle="modal">Contact</a></li>

			</ul>

		</div>

	</div>

</div>

<div class="container"  style="text-align:center;">
	<div class="jumbotron">
		<h2>Hello World</h2>
		<p>Practising My first website</p>
		<a class="btn btn-default">Watch It!</a>
		<a class="btn btn-info">Tweet It!</a>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-3">
			<h3><a href="#">Get Started..</a></h3>
			<p>Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
			Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
		Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.</p>
		<a href="/readArticlePage" class="btn btn-default">Read More..</a>
		</div>

		<div class="col-md-3">
			<h3><a href="#">Get Started..</a></h3>
			<p>Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
			Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
		Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.</p>
		<a href="/readArticlePage" class="btn btn-default">Read More..</a>
		</div>

		<div class="col-md-3">
			<h3><a href="#">Get Started..</a></h3>
			<p>Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
			Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
		Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.</p>
		<a href="/readArticlePage" class="btn btn-default">Read More..</a>
		</div>

		<div class="col-md-3">
			<h3><a href="#">Get Started..</a></h3>
			<p>Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
			Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.
		Donec ullamcorper nulla non metus auctor fringilla.Donec ullamcorper nulla non metus auctor fringilla.</p>
		<a href="/readArticlePage" class="btn btn-default">Read More..</a>
		</div>

	</div>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
	<div class="container">
		<p class="navbar-text pull-left">Site by Prabhjot</p>
		<a href="/subscribePage" class="navbar-btn  btn-danger btn pull-right">Subscribe</a>
	</div>
</div>

<div id = "contact" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="form-horizontal">
				<div class="modal-header">
					<h4>Contact Us</h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
								<label for="contact-name" class="col-lg-2 control-label">Name</label>
								<div class="col-lg-10">
									<input type="text" class="form-control" id="contact-name" placeholder="Full Name">
								</div>
					</div>
					<div class="form-group">
								<label for="contact-email" class="col-lg-2 control-label">Email</label>
								<div class="col-lg-10">
									<input type="text" class="form-control" id="contact-email" placeholder="you@example.com">
								</div>
					</div>
					<div class="form-group">
								<label for="message" class="col-lg-2 control-label">Message</label>
								<div class="col-lg-10">
									<textarea class="form-control" id="message" placeholder="" rows="8"></textarea>
								</div>
					</div>
				</div>
				<div class="modal-footer">
					<button class="btn btn-primary" type="submit">Send</button>
					<a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
				</div>
			</form>
		</div>
	</div>
</div>

app/views/welcome/subscribePage.html.erb
<h1>Subscribed</h1>